### ISSUE TITLE
Not detecting save updates in certain situations

### ISSUE THREAD

**Issue by Razzmatazzz** [Razzmatazzz/ValheimSaveShield#10]
There's at least one report of the app not detecting save file changes and automatically backing up. I haven't been able to reproduce this myself, so I'm not sure what's causing it.

**Comment by AnthonyWatson** [comment]
I can confirm this.

It was working for me up through 0.3.1.0 I think, as I was keeping the app up to date and my last autosaves are from 2/16 at 10:21PM (pacific time).

I updated to 0.3.3.0 but that still didn't fix it.  Went back to 0.3.1.0 and it isn't working.

I noticed Avast Cybercapture was flagging it, but even putting the VSS folder as an exception the issue still persists.

Might go back to 0.1.00 and slowly update to see if a specific version makes it not work?

**Comment by Razzmatazzz** [comment]
This week's game update initially broke detection of Dave file changes. I found a fix that works for me, but I'm not sure why it wouldn't work for others. I might have to make a noisy logging version for folks experiencing this issue to run so I can get more visibility into the issue.

**Comment by Razzmatazzz** [comment]
Someone else reported that it's not making new backups when it's reached the number for maximum backups to keep. This could be the same issue. If you're at the backup limit, could you delete your oldest backup or increase the limit and see if that allows it to automatically save again?

It successfully clears out the oldest backups for me, but at least this is a place to start.

**Comment by AnthonyWatson** [comment]
I'm going to do some troubleshooting.  Per your suggestion, I've deleted all but my most recent character save.

I also did a fresh install of Avast and put the VSS folder as an exception.  Should know pretty quick if it fixes it; I'll keep you posted!

Let me know if you want me to try a logging version; I'm happy to get you some more data.

**Comment by Razzmatazzz** [comment]
[vss-test.zip](https://github.com/Razzmatazzz/ValheimSaveShield/files/6013292/vss-test.zip)
I fixed some bugs with the interface that might have been helping to cause this. This is a noisy version that logs about a lot of factors that influence whether a backup is made.

**Comment by AnthonyWatson** [comment]
Thanks @Razzmatazzz!  I deleted the subfolders in %AppData%\Local\ValheimSaveShield and will give the test VSS program a try this weekend.

In case anyone with this issue needs a stopgap until VSS starts working, I found this to set up a USB drive to automatically backup my Valheim folder every 10 mins:

[](https://www.ubackup.com/windows-10/backup-specific-folders-windows-10.html)

VSS is a lot more elegant solution though.

**Comment by AnthonyWatson** [comment]
Hey @Razzmatazzz, I used the test VSS version for a couple hours tonight.

Issue still persists.  Saves are only backed up manually when I launch the program and a new save is present.

I enabled the log file but am not seeing much data in it; doesn't seem like any additional logging compared to the old versions.

Let me know how I can help!

**Comment by Razzmatazzz** [comment]
[vss-test.zip](https://github.com/Razzmatazzz/ValheimSaveShield/files/6014342/vss-test.zip)
The log file only contains what's shown in the log tab of the app. Here's a new version that should display messages about the world and character save file watchers when the app starts.

**Comment by Razzmatazzz** [comment]
To clarify, using that test build, you should see lines line the following in the log tab:
2/20/2021 8:29:57 AM: TEST - valid path for world save watcher,  Autobackup is set to True
2/20/2021 8:29:57 AM: TEST - valid path for character save watcher,  Autobackup is set to True

**Comment by Blixtmen** [comment]
Auto-backups doesn't work for me at all either, and can only do a manual backup upon first start of the program

**Comment by nf3ction** [comment]
VSS is not automatically saving for me either.  I launch it, it is not backed up, I can click the save icon to back it up, then it says it is backed up until I close an relaunch VSS.

I am using the new test version that was posted here.

Quit the game at 3:07 an no save, but the icon says it is up to date
![image](https://user-images.githubusercontent.com/7354191/108609783-9e660080-738d-11eb-8041-3c075321fc20.png)
Log 
![image](https://user-images.githubusercontent.com/7354191/108609798-b3429400-738d-11eb-829b-491ae2c7be26.png)
Launching the client again, you see its out of date
![image](https://user-images.githubusercontent.com/7354191/108609811-c3f30a00-738d-11eb-8237-98cb7438598c.png)
Log 
![image](https://user-images.githubusercontent.com/7354191/108609815-ce150880-738d-11eb-88e9-3adae89adcd3.png)
After manually making a backup, its current again
![image](https://user-images.githubusercontent.com/7354191/108609825-d9683400-738d-11eb-88db-e81cffb50833.png)
Final Log if that helps
![image](https://user-images.githubusercontent.com/7354191/108609836-ed139a80-738d-11eb-87a4-b6068d6df58c.png)

**Comment by AnthonyWatson** [comment]
Here's my log using the latest test build provided here:

`2/20/2021 2:02:54 PM: Version 0.3.3.0
2/20/2021 2:02:54 PM: Save folder not set; reverting to default.
2/20/2021 2:02:54 PM: Backup folder not set; reverting to default.
2/20/2021 2:02:54 PM: TEST - valid path for world save watcher,  Autobackup is set to True
2/20/2021 2:02:54 PM: TEST - valid path for character save watcher,  Autobackup is set to True

2/20/2021 2:39:07 PM: Version 0.3.3.0
2/20/2021 2:39:07 PM: TEST - valid path for world save watcher,  Autobackup is set to True
2/20/2021 2:39:07 PM: TEST - valid path for character save watcher,  Autobackup is set to True
2/20/2021 2:39:15 PM: Deleting excess backup leif erikson 1251 (2/19/2021 10:13:48 AM)
2/20/2021 2:39:15 PM: Backup of character leif erikson completed!
2/20/2021 2:39:58 PM: Backup "leif erikson 3761" (2/19/2021 10:48:43 AM) deleted.
2/20/2021 2:40:00 PM: Backup "leif erikson 954" (2/19/2021 11:19:56 AM) deleted.
2/20/2021 2:40:03 PM: Backup "leif erikson 378" (2/19/2021 4:43:14 PM) deleted.
2/20/2021 2:40:06 PM: Backup "leif erikson 9288" (2/19/2021 5:03:15 PM) deleted.
2/20/2021 2:40:09 PM: Backup "leif erikson 9279" (2/19/2021 5:23:16 PM) deleted.
2/20/2021 2:40:11 PM: Backup "leif erikson 9527" (2/19/2021 5:43:17 PM) deleted.
2/20/2021 2:40:14 PM: Backup "leif erikson 5182" (2/19/2021 6:03:18 PM) deleted.
2/20/2021 2:40:16 PM: Backup "leif erikson 517" (2/19/2021 6:23:19 PM) deleted.
2/20/2021 2:40:18 PM: Backup "leif erikson 2348" (2/19/2021 6:29:55 PM) deleted.

2/20/2021 2:40:41 PM: Version 0.3.3.0
2/20/2021 2:40:42 PM: TEST - valid path for world save watcher,  Autobackup is set to True
2/20/2021 2:40:42 PM: TEST - valid path for character save watcher,  Autobackup is set to True

2/20/2021 2:50:46 PM: Version 0.3.3.0
2/20/2021 2:50:46 PM: TEST - valid path for world save watcher,  Autobackup is set to True
2/20/2021 2:50:46 PM: TEST - valid path for character save watcher,  Autobackup is set to True
2/20/2021 2:50:51 PM: Backup of character leif erikson completed!`

As others have said, it won't back up manually, only when I close and reopen the program, provided there's a new (not backed up) save.  Seems like everything is working except the automatic backup.

**Comment by Razzmatazzz** [comment]
Based on these logs, it seems the FileWatcher object Changed/Created events are not firing for some reason. They work on my end, so it seems like there's something intermediating this. Is there anything slightly unusual with the systems setups for everyone experiencing this issue (running Windows in a VM, etc.)? Is everyone using a user account with admin privileges?

**Comment by nf3ction** [comment]
I am not running on a VM and user account has admin privileges. The only weird thing I can think of is I have Valheim stored on a different HDD than the OS.

**Comment by Razzmatazzz** [comment]
[vss-test.zip](https://github.com/Razzmatazzz/ValheimSaveShield/files/6018342/vss-test.zip)
I'm also running the game on a different drive than my OS, so that can't be the problem. The attached test version expands the types of file changes that will trigger the autosave event. It might help, but I'm kind of shooting blind here.

**Comment by AnthonyWatson** [comment]
I'm running Win10 Home, whatever the latest update is.

I know Avast was flagging some of the builds, but even with it disabled the issue persists.  I even tried running VSS as an administrator and that didn't change anything (my account is an admin).

I will say the previous builds worked for me and I didn't change anything on my PC.

I'll likely be playing again later today so I'll try the latest test VSS to see if that helps.

**Comment by Razzmatazzz** [comment]
I'm on Win10 Pro, so that's one difference. I wouldn't expect it to actually matter for these purposes, though.

This week's game update broke the original save detection. I made a fix that seems to work for most folks. My suspicion is that if you downgrade to a previous version of the app that was working for you, it will no longer work.

**Comment by AnthonyWatson** [comment]
That's correct.  When I noticed it wasn't working anymore I downgraded to an older version I think worked, followed by the first release; both didn't work.

**Comment by cproxy** [comment]
Not working here either.

Win10, have to reopen VSS to save again.  No autosaves, no manual saves after the first manual.

**Comment by Razzmatazzz** [comment]
Has anyone been able to try [the latest test build I posted](https://github.com/Razzmatazzz/ValheimSaveShield/issues/10#issuecomment-782912349)? It makes the file change detection a bit more aggressive for world saves.

**Comment by AnthonyWatson** [comment]
I used the latest build last night; the same issue persists.

When you open VSS and a new save (not backed up via VSS) is present, is the expected behavior for VSS to let you back it up manually?  Not sure if it's supposed to be automatic.

Judging by the bottom-left icon, it seems like save detection is working only when the program is initially launched.  I assume that's the same method used to autodetect a new save.  Similarly for backups, the manual backup works perfectly, and I'd assume that's how auto backup works.

I think the issue might have to do with the timer used to detect new saves.  If the timeout isn't triggering, it won't look for a new save, and thus won't back it up.

I'm not too familiar with C#, but could a TEST line be added to make sure it's attempting to check for a new save every 10 mins?

**Comment by Razzmatazzz** [comment]
Your assumptions are incorrect.

When the app launches, it iterates through all the world and character saves and checks whether they have corresponding backups. If any are missing backups, then the "not backed up" status is displayed.

Then, the app sets up a FileSystemWatcher object to watch world save files and another FileSystemWatcher object to watch character save files. When either of these objects detects a change in a save file, the app checks whether a backup of that save file has been made in the last 10 minutes (or however long the user has set) and then makes a backup if it's been longer than that.

The problem is that (for only some users) the FileSystemWatcher objects either aren't detecting save file changes or aren't firing the events related to save file changes. I can't for the life of me figure out why. And my inability to reproduce the problem significantly hampers my ability to troubleshoot.

**Comment by AnthonyWatson** [comment]
Ah, I see.  In case this info is helpful, here are the details of which Win10 version I'm running:

Windows 10 Home
Version 20H2 (OS Build 19042.804)

I checked and I haven't installed any updates between 2/12 and 2/20 and I bought Valheim on 2/12.  Like I said, I think VSS stopped working around 2/16.

I did some Googling and found some posts about FileSystemWatcher not being reliable.  Not sure about that, but maybe this issue is falling into that category?  Searching for FileSystemWatcher alternatives brought me here numerous times:

https://github.com/dotnet/corefxlab/tree/master/src/System.IO.FileSystem.Watcher.Polling

Not sure what percentage of VSS users this issue is affecting, so idk if redoing so much of the core code is worth it or not.

As I've said before, if there's anything I can help with let me know.

**Comment by Razzmatazzz** [comment]
[vss-test-2020-02-22.zip](https://github.com/Razzmatazzz/ValheimSaveShield/files/6025124/vss-test-2020-02-22.zip)
Here's another test version that cranks up the aggressiveness of the FileSystemWatchers.

**Comment by AnthonyWatson** [comment]
Just tried the latest VSS from 2/22/2020

Still not automatically backing up, although I didn't try disabling Avast or running it as an administrator.  Still, the log seems a little more promising

_2/22/2021 7:18:39 PM: Version 0.3.3.0
2/22/2021 7:18:39 PM: Save folder not set; reverting to default.
2/22/2021 7:18:39 PM: Backup folder not set; reverting to default.
**2/22/2021 7:19:24 PM: C:\Users\antho\AppData\LocalLow\IronGate\Valheim\characters\leif erikson.fch Changed**

2/22/2021 7:54:35 PM: Version 0.3.3.0
2/22/2021 7:54:37 PM: Deleting excess backup leif erikson 7229 (2/21/2021 3:18:23 PM)
2/22/2021 7:54:37 PM: Backup of character leif erikson completed!

2/22/2021 8:07:49 PM: Version 0.3.3.0
2/22/2021 8:07:52 PM: Deleting excess backup leif erikson 8454 (2/21/2021 3:41:58 PM)
2/22/2021 8:07:52 PM: Backup of character leif erikson completed!

2/22/2021 8:51:31 PM: Version 0.3.3.0
2/22/2021 8:51:34 PM: Deleting excess backup leif erikson 7895 (2/21/2021 7:38:13 PM)
2/22/2021 8:51:34 PM: Backup of character leif erikson completed!

2/22/2021 9:21:15 PM: Version 0.3.3.0
2/22/2021 9:21:19 PM: Deleting excess backup leif erikson 6946 (2/21/2021 7:58:14 PM)
2/22/2021 9:21:19 PM: Backup of character leif erikson completed!_

As you can see, the program noticed that my character changed.  I think this happened when I launched Valheim?

@Razzmatazzz, just to confirm, you're saying the 2/17 patch caused save change detection to break, and the fix that worked on your end (FileSystemWatcher?) isn't working for us.

At least that explains why VSS stopped working correctly, not due to something on my end.

**Comment by Razzmatazzz** [comment]
[vss-test-2021-02-23.zip](https://github.com/Razzmatazzz/ValheimSaveShield/files/6028898/vss-test-2021-02-23.zip)
Thank you for testing that version. Yes, that version was detecting when Valheim was "accessing" save files, but apparently it still wasn't triggering for actual save file changes. A new test version is attached that tries another method for detecting changes.

Correct. The 2/17 patch broke save file change detection for _everybody_, I made a fix that works for me but apparently not for all. The app was using FileSystemWatcher both before and after the patch. Before the patch, it was only responding to "last write time" events. After the patch, I changed it to also respond to "file created" events (which worked for me). This newest test also adds in "file renamed" events, which according to my testing also fire when a save is updated.

**Comment by nf3ction** [comment]
So, using the new version, I have to manually save it when I launch the program.  It is automatically backing up my world save, but not my character save.  The final save I did was another manual save when I was done playing.

`2/23/2021 10:30:31 AM: Version 0.3.3.0
2/23/2021 10:30:38 AM: Backup of world BensServer completed!
2/23/2021 10:30:38 AM: Backup of character ganah completed!
2/23/2021 10:32:04 AM: C:\Users\nf3ction.DESKTOP-GR57K3N\AppData\LocalLow\IronGate\Valheim\worlds\BensServer.db.old Renamed
2/23/2021 10:32:04 AM: C:\Users\nf3ction.DESKTOP-GR57K3N\AppData\LocalLow\IronGate\Valheim\worlds\BensServer.db.old Renamed
2/23/2021 10:32:04 AM: C:\Users\nf3ction.DESKTOP-GR57K3N\AppData\LocalLow\IronGate\Valheim\worlds\BensServer.db Renamed
2/23/2021 10:32:04 AM: C:\Users\nf3ction.DESKTOP-GR57K3N\AppData\LocalLow\IronGate\Valheim\worlds\BensServer.db Renamed
2/23/2021 10:32:05 AM: Backup of world BensServer completed!
2/23/2021 11:10:58 AM: C:\Users\nf3ction.DESKTOP-GR57K3N\AppData\LocalLow\IronGate\Valheim\worlds\BensServer.db.old Renamed
2/23/2021 11:10:58 AM: C:\Users\nf3ction.DESKTOP-GR57K3N\AppData\LocalLow\IronGate\Valheim\worlds\BensServer.db.old Renamed
2/23/2021 11:10:58 AM: C:\Users\nf3ction.DESKTOP-GR57K3N\AppData\LocalLow\IronGate\Valheim\worlds\BensServer.db Renamed
2/23/2021 11:10:58 AM: C:\Users\nf3ction.DESKTOP-GR57K3N\AppData\LocalLow\IronGate\Valheim\worlds\BensServer.db Renamed
2/23/2021 11:10:59 AM: Backup of world BensServer completed!
2/23/2021 11:28:16 AM: C:\Users\nf3ction.DESKTOP-GR57K3N\AppData\LocalLow\IronGate\Valheim\worlds\BensServer.db.old Renamed
2/23/2021 11:28:16 AM: C:\Users\nf3ction.DESKTOP-GR57K3N\AppData\LocalLow\IronGate\Valheim\worlds\BensServer.db.old Renamed
2/23/2021 11:28:16 AM: C:\Users\nf3ction.DESKTOP-GR57K3N\AppData\LocalLow\IronGate\Valheim\worlds\BensServer.db Renamed
2/23/2021 11:28:16 AM: C:\Users\nf3ction.DESKTOP-GR57K3N\AppData\LocalLow\IronGate\Valheim\worlds\BensServer.db Renamed
2/23/2021 11:28:17 AM: Deleting excess backup BensServer 8127 (2/19/2021 8:15:07 PM)
2/23/2021 11:28:17 AM: Backup of world BensServer completed!
2/23/2021 11:31:17 AM: C:\Users\nf3ction.DESKTOP-GR57K3N\AppData\LocalLow\IronGate\Valheim\worlds\BensServer.db.old Renamed
2/23/2021 11:31:17 AM: C:\Users\nf3ction.DESKTOP-GR57K3N\AppData\LocalLow\IronGate\Valheim\worlds\BensServer.db.old Renamed
2/23/2021 11:31:17 AM: C:\Users\nf3ction.DESKTOP-GR57K3N\AppData\LocalLow\IronGate\Valheim\worlds\BensServer.db Renamed
2/23/2021 11:31:17 AM: C:\Users\nf3ction.DESKTOP-GR57K3N\AppData\LocalLow\IronGate\Valheim\worlds\BensServer.db Renamed
2/23/2021 11:31:18 AM: Save change detected, but 6.95 minutes, left until next backup
2/23/2021 11:51:35 AM: C:\Users\nf3ction.DESKTOP-GR57K3N\AppData\LocalLow\IronGate\Valheim\worlds\BensServer.db.old Renamed
2/23/2021 11:51:35 AM: C:\Users\nf3ction.DESKTOP-GR57K3N\AppData\LocalLow\IronGate\Valheim\worlds\BensServer.db.old Renamed
2/23/2021 11:51:35 AM: C:\Users\nf3ction.DESKTOP-GR57K3N\AppData\LocalLow\IronGate\Valheim\worlds\BensServer.db Renamed
2/23/2021 11:51:35 AM: C:\Users\nf3ction.DESKTOP-GR57K3N\AppData\LocalLow\IronGate\Valheim\worlds\BensServer.db Renamed
2/23/2021 11:51:36 AM: Deleting excess backup BensServer 1190 (2/19/2021 8:22:35 PM)
2/23/2021 11:51:36 AM: Backup of world BensServer completed!
2/23/2021 11:51:44 AM: Backup of character ganah completed!
`

**Comment by Razzmatazzz** [comment]
[vss-test-2021-020-23 02.zip](https://github.com/Razzmatazzz/ValheimSaveShield/files/6031274/vss-test-2021-020-23.02.zip)
Thanks for testing. The attached should fix automatic saves  for characters. Once I get confirmation that it's working, I will push out a new release.

**Comment by nf3ction** [comment]
Saved the game manually and it backed up the world automatically
Quit the game and it backed up the character automatically

Automatic backups of characters and worlds are working while I am playing as well

`2/23/2021 12:06:00 PM: Version 0.3.3.0
2/23/2021 12:19:13 PM: C:\Users\nf3ction.DESKTOP-GR57K3N\AppData\LocalLow\IronGate\Valheim\worlds\BensServer.db.old Renamed
2/23/2021 12:19:13 PM: C:\Users\nf3ction.DESKTOP-GR57K3N\AppData\LocalLow\IronGate\Valheim\worlds\BensServer.db Renamed
2/23/2021 12:19:14 PM: object: ValheimSaveShield.SaveTimer
2/23/2021 12:19:14 PM: Deleting excess backup BensServer 9595 (2/20/2021 12:33:15 PM)
2/23/2021 12:19:14 PM: Backup of world BensServer completed!
2/23/2021 12:19:21 PM: C:\Users\nf3ction.DESKTOP-GR57K3N\AppData\LocalLow\IronGate\Valheim\characters\ganah.fch.old Renamed
2/23/2021 12:19:21 PM: C:\Users\nf3ction.DESKTOP-GR57K3N\AppData\LocalLow\IronGate\Valheim\characters\ganah.fch Renamed
2/23/2021 12:19:22 PM: object: ValheimSaveShield.SaveTimer
2/23/2021 12:19:22 PM: Backup of character ganah completed!
2/23/2021 12:19:22 PM: C:\Users\nf3ction.DESKTOP-GR57K3N\AppData\LocalLow\IronGate\Valheim\worlds\BensServer.db.old Renamed
2/23/2021 12:19:22 PM: C:\Users\nf3ction.DESKTOP-GR57K3N\AppData\LocalLow\IronGate\Valheim\worlds\BensServer.db Renamed
2/23/2021 12:19:23 PM: object: ValheimSaveShield.SaveTimer
2/23/2021 12:19:23 PM: Save change detected, but 9.82 minutes left until next backup is due.
2/23/2021 12:39:48 PM: C:\Users\nf3ction.DESKTOP-GR57K3N\AppData\LocalLow\IronGate\Valheim\characters\ganah.fch.old Renamed
2/23/2021 12:39:48 PM: C:\Users\nf3ction.DESKTOP-GR57K3N\AppData\LocalLow\IronGate\Valheim\characters\ganah.fch Renamed
2/23/2021 12:39:49 PM: object: ValheimSaveShield.SaveTimer
2/23/2021 12:39:49 PM: Deleting excess backup ganah 9903 (2/19/2021 8:15:06 PM)
2/23/2021 12:39:49 PM: Backup of character ganah completed!
2/23/2021 12:39:51 PM: C:\Users\nf3ction.DESKTOP-GR57K3N\AppData\LocalLow\IronGate\Valheim\worlds\BensServer.db.old Renamed
2/23/2021 12:39:51 PM: C:\Users\nf3ction.DESKTOP-GR57K3N\AppData\LocalLow\IronGate\Valheim\worlds\BensServer.db Renamed
2/23/2021 12:39:52 PM: object: ValheimSaveShield.SaveTimer
2/23/2021 12:39:52 PM: Deleting excess backup BensServer 3415 (2/20/2021 2:45:13 PM)
2/23/2021 12:39:52 PM: Backup of world BensServer completed!
2/23/2021 12:59:50 PM: C:\Users\nf3ction.DESKTOP-GR57K3N\AppData\LocalLow\IronGate\Valheim\characters\ganah.fch.old Renamed
2/23/2021 12:59:50 PM: C:\Users\nf3ction.DESKTOP-GR57K3N\AppData\LocalLow\IronGate\Valheim\characters\ganah.fch Renamed
2/23/2021 12:59:51 PM: object: ValheimSaveShield.SaveTimer
2/23/2021 12:59:51 PM: Deleting excess backup ganah 7999 (2/19/2021 8:22:35 PM)
2/23/2021 12:59:51 PM: Backup of character ganah completed!
2/23/2021 12:59:52 PM: C:\Users\nf3ction.DESKTOP-GR57K3N\AppData\LocalLow\IronGate\Valheim\worlds\BensServer.db.old Renamed
2/23/2021 12:59:52 PM: C:\Users\nf3ction.DESKTOP-GR57K3N\AppData\LocalLow\IronGate\Valheim\worlds\BensServer.db Renamed
2/23/2021 12:59:53 PM: object: ValheimSaveShield.SaveTimer
2/23/2021 12:59:53 PM: Deleting excess backup BensServer 989 (2/20/2021 3:03:28 PM)
2/23/2021 12:59:53 PM: Backup of world BensServer completed!
`

**Comment by Razzmatazzz** [comment]
Great, once @AnthonyWatson confirms it's working for him also, I'll do a release.

**Comment by tgoVIPER** [comment]
Phew, thought it was just me.
I'm having the exact same issues described in this thread.
I'll try out the test version and see if it works.

Thanks!

**Comment by AnthonyWatson** [comment]
@Razzmatazzz I'd say this is fixed.  Played for ~40 minutes and had 2 auto backups occur:

2/23/2021 1:00:51 PM: Version 0.3.3.0
2/23/2021 1:00:51 PM: Save folder not set; reverting to default.
2/23/2021 1:00:51 PM: Backup folder not set; reverting to default.
2/23/2021 1:21:52 PM: C:\Users\antho\AppData\LocalLow\IronGate\Valheim\characters\leif erikson.fch.old Renamed
2/23/2021 1:21:52 PM: C:\Users\antho\AppData\LocalLow\IronGate\Valheim\characters\leif erikson.fch Renamed
2/23/2021 1:21:53 PM: object: ValheimSaveShield.SaveTimer
2/23/2021 1:21:53 PM: Deleting excess backup leif erikson 7957 (2/21/2021 8:38:15 PM)
2/23/2021 1:21:53 PM: Backup of character leif erikson completed!
2/23/2021 1:41:53 PM: C:\Users\antho\AppData\LocalLow\IronGate\Valheim\characters\leif erikson.fch.old Renamed
2/23/2021 1:41:53 PM: C:\Users\antho\AppData\LocalLow\IronGate\Valheim\characters\leif erikson.fch Renamed
2/23/2021 1:41:54 PM: object: ValheimSaveShield.SaveTimer
2/23/2021 1:41:54 PM: Deleting excess backup leif erikson 7833 (2/21/2021 8:58:16 PM)
2/23/2021 1:41:54 PM: Backup of character leif erikson completed!
2/23/2021 1:42:02 PM: C:\Users\antho\AppData\LocalLow\IronGate\Valheim\characters\leif erikson.fch.old Renamed
2/23/2021 1:42:02 PM: C:\Users\antho\AppData\LocalLow\IronGate\Valheim\characters\leif erikson.fch Renamed
2/23/2021 1:42:03 PM: object: ValheimSaveShield.SaveTimer
2/23/2021 1:42:03 PM: Save change detected, but 9.82 minutes left until next backup is due.
2/23/2021 1:55:04 PM: Deleting excess backup leif erikson 6017 (2/21/2021 9:18:17 PM)
2/23/2021 1:55:04 PM: Backup of character leif erikson completed!

Out of curiosity, is it supposed to auto-backup after the game is closed?  I exited at 1:42:03 PM and it detected the change 1 second later.  I left VSS running for a bit but it didn't backup the save until I did it manually.

That being said, autosave while gaming has been fixed it seems, so that's good :)

**Comment by Razzmatazzz** [comment]
No, it does not auto backup when the game is closed if the last backup was less time ago than the backup interval.

I just put out the new version. Thanks everyone for bringing the issue and helping to troubleshoot it!
